name: Trigger auto deployment for hackaton-mental-health

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hackaton-mental-health-AutoDeployTrigger-a4b9da34-f219-451f-a70b-96f75fad2a39.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HACKATONMENTALHEALTH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HACKATONMENTALHEALTH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HACKATONMENTALHEALTH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: mindiriacr.azurecr.io
          registryUsername: ${{ secrets.HACKATONMENTALHEALTH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HACKATONMENTALHEALTH_REGISTRY_PASSWORD }}
          containerAppName: hackaton-mental-health
          resourceGroup: hackaton-dicoding
          imageToBuild: mindiriacr.azurecr.io/hackaton-mental-health:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


